
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  # namespace: pricing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: umarhayat13/pricing-service:${DOCKER_TAG}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15 
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30 
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
