apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-pricing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: umarhayat13/pricing-service:main-11
        command: ["/bin/sh", "-c"]
        args:
          - "pip install aiohttp && python /app/src/main/python/webapp.py"
        ports:
        - containerPort: 80